### ISSUE TITLE
Update Readme to include TDP example usage

### ISSUE THREAD

**Issue by tloki** [agoose77/throttlestop#3]
I don't know how to use tdp ajdustment option

tried this to up my Xiaomi Notebook Pro (i7 8550U/16GB/MX150)to 45W (supported on Windows):

`/usr/bin/python3 -m throttlestop tdp "{\"power\": 45}"`

without success

**Comment by agoose77** [comment]
You can see the input that is expected by just printing the output, e.g.
`sudo throttlestop tdp`

The API at present takes the JSON object and applies it as a delta to the output, so you would want to do something like

```sh
sudo throttlestop tdp "{\"first\": {\"power_limit\": 45.0}}"
```

**Comment by tloki** [comment]
Thanks!
