### ISSUE TITLE
required Python 3.6 !

### ISSUE THREAD

**Issue by SalimF** [agoose77/throttlestop#4]
Hi I just read the Repositories file I folow installation instruction but I got this error :-   
`ERROR: throttlestop-0.0.3 requires Python '>=3.6,<4.0' but the running Python is 2.7.15`
aren't setup tools able to detect Python 3.6 installation path , as you know most linux distro uses Python 2.7 as default for compatibility reason !
any wahy how could I add full Python path to the setup ! I'm not that expert with Python programs at all .

**Comment by agoose77** [comment]
Hi salim, most distros now use python3.6 as their system python. You need to install using python3, which will then be used to run the script.

**Comment by SalimF** [comment]
Thanks for reply everything works fine now , I was have to install it manually not via pip 
`sudo python3.6  ./setup.py  install`
