### ISSUE TITLE
Failed to start throttlestop.

### ISSUE THREAD

**Issue by SalimF** [agoose77/throttlestop#5]
When I start the service I got it fail , this is `systemctl status throttlestop.service`  error log 

```
● throttlestop.service - throttlestop
   Loaded: loaded (/etc/systemd/system/throttlestop.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2019-09-15 12:12:24 CEST; 15s ago
  Process: 6088 ExecStart=/usr/bin/python3.6 -m throttlestop voltage {"cache": -149, "cpu": -149} (code=exited, status=1/FAILURE)
 Main PID: 6088 (code=exited, status=1/FAILURE)

Sep 15 12:12:24  python3.6[6088]:   File "/usr/local/lib/python3.6/dist-packages/plumbum-1.6.7-py3.6.egg/plumbum/commands/processes.py", line 23, in _check_proces
Sep 15 12:12:24  python3.6[6088]:     proc.verify(retcode, timeout, stdout, stderr)
Sep 15 12:12:24  python3.6[6088]:   File "/usr/local/lib/python3.6/dist-packages/plumbum-1.6.7-py3.6.egg/plumbum/machines/base.py", line 26, in verify
Sep 15 12:12:24  python3.6[6088]:     stderr)
Sep 15 12:12:24  python3.6[6088]: plumbum.commands.processes.ProcessExecutionError: Command line: ['/usr/sbin/wrmsr', '0x150', '0x80000011ece00000']
Sep 15 12:12:24  python3.6[6088]: Exit code: 4
Sep 15 12:12:24  python3.6[6088]: Stderr:  | wrmsr: CPU 0 cannot set MSR 0x00000150 to 0x80000011ece00000
Sep 15 12:12:24  systemd[1]: throttlestop.service: Main process exited, code=exited, status=1/FAILURE
Sep 15 12:12:24  systemd[1]: throttlestop.service: Failed with result 'exit-code'.
Sep 15 12:12:24  systemd[1]: Failed to start throttlestop.
```
My system in `Linux mint 19` kernel version `4.18.14-041814-generic` my CPU is `core i5-3210M` "Ivy Bridge"
here is errors I got when excute the command directly 
```
plumbum.commands.processes.ProcessExecutionError: Command line: ['/usr/sbin/wrmsr', '0x150', '0x80000011ece00000']
Exit code: 4
Stderr:  | wrmsr: CPU 0 cannot set MSR 0x00000150 to 0x80000011ece00000
```

**Comment by agoose77** [comment]
Hi @SalimF, 

Thank you for your patience, I missed this issue apparently.

If you're still interested, it would be worth finding the register codes for the particular CPU that you're using. It is likely that I wrote this for my particular CPU set and didn't check compatibility with other CPUs.

**Comment by SalimF** [comment]
@agoose77  `it would be worth finding the register codes for the particular CPU that you're using ` ,

Thanks that's will be very nice , if you couldn't find my CPU registers values I could run  `ThrottleStop` on windows and post it log here .
My CPU is 
`Intel() Core() i5-3210M CPU @ 2.50GHz`

**Comment by P1dum** [comment]
Hello agoose,
I also have an error to start the service, but with the status=2/INVALIDARGUMENT error.

Here you can find the systemctl status throttlestop.service :

> ● throttlestop.service - throttlestop
>    Loaded: loaded (/etc/systemd/system/throttlestop.service; enabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Thu 2020-01-30 15:48:56 CET; 12s ago
>   Process: 26806 ExecStart=/usr/bin/python3 -m throttlestop /usr/bin/python3 -m throttlestop voltage {"cache": -149, "cpu": -149} (code=exited, status=2)
>  Main PID: 26806 (code=exited, status=2)
> 
> janv. 30 15:48:55 pidum-PC systemd[1]: Starting throttlestop...
> janv. 30 15:48:56 pidum-PC python3[26806]: usage: __main__.py [-h] {tdp,voltage,temperature} ...
> janv. 30 15:48:56 pidum-PC python3[26806]: __main__.py: error: invalid choice: '/usr/bin/python3' (choose from 'tdp', 'voltage', 'temperature')
> janv. 30 15:48:56 pidum-PC systemd[1]: throttlestop.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
> janv. 30 15:48:56 pidum-PC systemd[1]: throttlestop.service: Failed with result 'exit-code'.
> janv. 30 15:48:56 pidum-PC systemd[1]: Failed to start throttlestop.

I tried to copy-paste the config lines twice, same result.

Thanks
