### ISSUE TITLE
Unable to Install - No Matching Distribution

### ISSUE THREAD

**Issue by stephendt** [agoose77/throttlestop#6]
Howdy Folks,

Unfortunately I am presented with this error when trying to install via pip:

Collecting throttlestop
  Could not find a version that satisfies the requirement throttlestop (from versions: )
No matching distribution found for throttlestop

I am running Proxmox 6.1.5 (Debian 10). Am I missing something?

**Comment by agoose77** [comment]
Hi @stephendt,

Nothing wrong on your end - I suspect you're not using Python 3.6, so I need to bump the supported versions!

**Comment by stephendt** [comment]
It was actually partially my fault as well - I needed to use pip3 instead of pip.

The command that worked for me was:

`pip3 install throttlestop`

Thanks!
